export const MOCK_PROVIDERS = [
  {
    id: 'harbour-bank',
    name: 'Harbour Bank',
    abn: '12 345 678 901',
    brandName: 'Harbour Bank',
    industry: 'banking',
    logoUri: 'https://example.com/logos/harbour-bank.png',
    websiteUri: 'https://harbourbank.example.com',
    cdrHolderId: 'harbour-bank-001',
  },
  {
    id: 'southern-cross-bank',
    name: 'Southern Cross Bank',
    abn: '98 765 432 109',
    brandName: 'Southern Cross Bank',
    industry: 'banking',
    logoUri: 'https://example.com/logos/scb.png',
    websiteUri: 'https://southerncrossbank.example.com',
    cdrHolderId: 'scb-001',
  },
  {
    id: 'pacific-coast-bank',
    name: 'Pacific Coast Bank',
    abn: '55 111 222 333',
    brandName: 'Pacific Coast Bank',
    industry: 'banking',
    logoUri: 'https://example.com/logos/pcb.png',
    websiteUri: 'https://pacificcoastbank.example.com',
    cdrHolderId: 'pcb-001',
  },
];

export const MOCK_PRODUCTS = {
  'harbour-bank': [
    {
      productId: 'hb-everyday-savings',
      effectiveFrom: '2024-01-01T00:00:00Z',
      effectiveTo: null,
      lastUpdated: '2025-01-15T00:00:00Z',
      productCategory: 'TRANS_AND_SAVINGS_ACCOUNTS',
      name: 'Harbour Everyday Saver',
      description: 'High-interest savings account with no monthly fees',
      brand: 'harbour-bank',
      brandName: 'Harbour Bank',
      applicationUri: 'https://harbourbank.example.com/apply/everyday-saver',
      isTailored: false,
      features: [
        { featureType: 'DIGITAL_BANKING', additionalInfo: 'Full online and mobile banking' },
        { featureType: 'NPP_PAYID', additionalInfo: 'PayID and PayTo supported' },
        { featureType: 'FREE_TXNS', additionalValue: 'UNLIMITED', additionalInfo: 'Unlimited free transactions' },
      ],
      constraints: [
        { constraintType: 'MIN_BALANCE', additionalValue: '1.00' },
      ],
      eligibility: [
        { eligibilityType: 'RESIDENCY', additionalInfo: 'Australian residents only' },
        { eligibilityType: 'MIN_AGE', additionalValue: '18' },
      ],
      fees: [],
      depositRates: [
        { depositRateType: 'BASE', rate: '0.0475', calculationFrequency: 'P1D', applicationFrequency: 'P1M', additionalInfo: 'Base rate 4.75% p.a.' },
        { depositRateType: 'BONUS', rate: '0.005', calculationFrequency: 'P1D', applicationFrequency: 'P1M', additionalInfo: 'Bonus 0.5% when you make 5+ purchases per month' },
      ],
      lendingRates: [],
    },
    {
      productId: 'hb-everyday-transaction',
      effectiveFrom: '2024-01-01T00:00:00Z',
      effectiveTo: null,
      lastUpdated: '2025-01-15T00:00:00Z',
      productCategory: 'TRANS_AND_SAVINGS_ACCOUNTS',
      name: 'Harbour Everyday Account',
      description: 'Fee-free everyday transaction account',
      brand: 'harbour-bank',
      brandName: 'Harbour Bank',
      applicationUri: 'https://harbourbank.example.com/apply/everyday',
      isTailored: false,
      features: [
        { featureType: 'DIGITAL_BANKING', additionalInfo: 'Mobile and internet banking' },
        { featureType: 'VISA_DEBIT', additionalInfo: 'Visa Debit card included' },
        { featureType: 'NPP_PAYID' },
      ],
      constraints: [],
      eligibility: [
        { eligibilityType: 'RESIDENCY', additionalInfo: 'Australian residents only' },
        { eligibilityType: 'MIN_AGE', additionalValue: '18' },
      ],
      fees: [],
      depositRates: [
        { depositRateType: 'BASE', rate: '0.0001', calculationFrequency: 'P1D', applicationFrequency: 'P1M', additionalInfo: '0.01% p.a. on account balance' },
      ],
      lendingRates: [],
    },
    {
      productId: 'hb-home-loan-variable',
      effectiveFrom: '2024-03-01T00:00:00Z',
      effectiveTo: null,
      lastUpdated: '2025-02-01T00:00:00Z',
      productCategory: 'RESIDENTIAL_MORTGAGES',
      name: 'Harbour Variable Home Loan',
      description: 'Competitive variable rate home loan with offset account',
      brand: 'harbour-bank',
      brandName: 'Harbour Bank',
      applicationUri: 'https://harbourbank.example.com/apply/home-loan',
      isTailored: false,
      features: [
        { featureType: 'OFFSET', additionalInfo: '100% offset account available' },
        { featureType: 'REDRAW', additionalInfo: 'Free unlimited redraws' },
        { featureType: 'DIGITAL_BANKING' },
      ],
      constraints: [
        { constraintType: 'MIN_LIMIT', additionalValue: '100000' },
        { constraintType: 'MAX_LIMIT', additionalValue: '5000000' },
      ],
      eligibility: [
        { eligibilityType: 'RESIDENCY', additionalInfo: 'Australian residents only' },
        { eligibilityType: 'MIN_AGE', additionalValue: '18' },
        { eligibilityType: 'EMPLOYMENT_STATUS', additionalInfo: 'Regular income required' },
      ],
      fees: [
        { name: 'Annual Fee', feeType: 'PERIODIC', amount: '395.00', additionalInfo: 'Charged annually' },
        { name: 'Application Fee', feeType: 'UPFRONT', amount: '600.00', additionalInfo: 'One-off application fee' },
      ],
      depositRates: [],
      lendingRates: [
        { lendingRateType: 'VARIABLE', rate: '0.0624', comparisonRate: '0.0641', calculationFrequency: 'P1D', applicationFrequency: 'P1M', additionalInfo: 'Variable rate 6.24% p.a. Comparison rate 6.41% p.a.' },
      ],
    },
  ],
  'southern-cross-bank': [
    {
      productId: 'scb-bonus-saver',
      effectiveFrom: '2024-01-01T00:00:00Z',
      effectiveTo: null,
      lastUpdated: '2025-01-10T00:00:00Z',
      productCategory: 'TRANS_AND_SAVINGS_ACCOUNTS',
      name: 'SCB Bonus Saver',
      description: 'Earn bonus interest with monthly deposit conditions',
      brand: 'southern-cross-bank',
      brandName: 'Southern Cross Bank',
      applicationUri: 'https://southerncrossbank.example.com/apply/bonus-saver',
      isTailored: false,
      features: [
        { featureType: 'DIGITAL_BANKING' },
        { featureType: 'NPP_PAYID' },
      ],
      constraints: [],
      eligibility: [
        { eligibilityType: 'RESIDENCY', additionalInfo: 'Australian residents only' },
        { eligibilityType: 'MIN_AGE', additionalValue: '18' },
      ],
      fees: [],
      depositRates: [
        { depositRateType: 'BASE', rate: '0.015', calculationFrequency: 'P1D', applicationFrequency: 'P1M', additionalInfo: 'Base rate 1.5% p.a.' },
        { depositRateType: 'BONUS', rate: '0.035', calculationFrequency: 'P1D', applicationFrequency: 'P1M', additionalInfo: 'Bonus rate 3.5% p.a. when you deposit $200+ per month' },
      ],
      lendingRates: [],
    },
    {
      productId: 'scb-credit-card',
      effectiveFrom: '2024-01-01T00:00:00Z',
      effectiveTo: null,
      lastUpdated: '2025-01-10T00:00:00Z',
      productCategory: 'CRED_AND_CHRG_CARDS',
      name: 'SCB Rewards Visa',
      description: 'Rewards credit card with travel benefits',
      brand: 'southern-cross-bank',
      brandName: 'Southern Cross Bank',
      applicationUri: 'https://southerncrossbank.example.com/apply/rewards-card',
      isTailored: false,
      features: [
        { featureType: 'REWARDS_POINTS', additionalInfo: '1.5 points per $1 spent' },
        { featureType: 'TRAVEL_INSURANCE', additionalInfo: 'Complimentary international travel insurance' },
        { featureType: 'DIGITAL_BANKING' },
        { featureType: 'COMPLEMENTARY_PRODUCT_DISCOUNTS', additionalInfo: 'Airport lounge access' },
      ],
      constraints: [
        { constraintType: 'MIN_LIMIT', additionalValue: '2000' },
        { constraintType: 'MAX_LIMIT', additionalValue: '30000' },
      ],
      eligibility: [
        { eligibilityType: 'MIN_INCOME', additionalValue: '35000', additionalInfo: 'Minimum income $35,000 p.a.' },
        { eligibilityType: 'MIN_AGE', additionalValue: '18' },
      ],
      fees: [
        { name: 'Annual Fee', feeType: 'PERIODIC', amount: '149.00', additionalInfo: 'Annual card fee' },
        { name: 'Late Payment Fee', feeType: 'EVENT', amount: '30.00', additionalInfo: 'Charged when minimum payment not made by due date' },
      ],
      depositRates: [],
      lendingRates: [
        { lendingRateType: 'PURCHASE', rate: '0.1999', comparisonRate: '0.1999', calculationFrequency: 'P1D', applicationFrequency: 'P1M', additionalInfo: 'Purchase rate 19.99% p.a.' },
        { lendingRateType: 'CASH_ADVANCE', rate: '0.2199', comparisonRate: '0.2199', calculationFrequency: 'P1D', applicationFrequency: 'P1M', additionalInfo: 'Cash advance rate 21.99% p.a.' },
      ],
    },
  ],
  'pacific-coast-bank': [
    {
      productId: 'pcb-business-account',
      effectiveFrom: '2024-01-01T00:00:00Z',
      effectiveTo: null,
      lastUpdated: '2025-01-20T00:00:00Z',
      productCategory: 'TRANS_AND_SAVINGS_ACCOUNTS',
      name: 'PCB Business Essentials',
      description: 'Business transaction account for SMEs',
      brand: 'pacific-coast-bank',
      brandName: 'Pacific Coast Bank',
      applicationUri: 'https://pacificcoastbank.example.com/apply/business-essentials',
      isTailored: false,
      features: [
        { featureType: 'DIGITAL_BANKING', additionalInfo: 'Business banking portal with payroll integration' },
        { featureType: 'NPP_PAYID' },
        { featureType: 'BILL_PAYMENT', additionalInfo: 'Batch payment processing' },
      ],
      constraints: [],
      eligibility: [
        { eligibilityType: 'BUSINESS', additionalInfo: 'Must be a registered Australian business' },
        { eligibilityType: 'RESIDENCY', additionalInfo: 'Business registered in Australia' },
      ],
      fees: [
        { name: 'Monthly Service Fee', feeType: 'PERIODIC', amount: '10.00', additionalInfo: '$10 per month, waived for first 3 months' },
        { name: 'Electronic Transaction Fee', feeType: 'TRANSACTION', amount: '0.00', additionalInfo: 'Free electronic transactions' },
        { name: 'Over-the-counter Fee', feeType: 'TRANSACTION', amount: '2.50', additionalInfo: '$2.50 per branch transaction' },
      ],
      depositRates: [
        { depositRateType: 'BASE', rate: '0.0001', calculationFrequency: 'P1D', applicationFrequency: 'P1M', additionalInfo: 'Nominal interest on credit balance' },
      ],
      lendingRates: [],
    },
    {
      productId: 'pcb-personal-loan',
      effectiveFrom: '2024-01-01T00:00:00Z',
      effectiveTo: null,
      lastUpdated: '2025-01-20T00:00:00Z',
      productCategory: 'PERS_LOANS',
      name: 'PCB Personal Loan',
      description: 'Fixed rate personal loan for any purpose',
      brand: 'pacific-coast-bank',
      brandName: 'Pacific Coast Bank',
      applicationUri: 'https://pacificcoastbank.example.com/apply/personal-loan',
      isTailored: false,
      features: [
        { featureType: 'DIGITAL_BANKING' },
        { featureType: 'EXTRA_REPAYMENTS', additionalInfo: 'Extra repayments allowed without penalty' },
      ],
      constraints: [
        { constraintType: 'MIN_LIMIT', additionalValue: '3000' },
        { constraintType: 'MAX_LIMIT', additionalValue: '50000' },
      ],
      eligibility: [
        { eligibilityType: 'MIN_INCOME', additionalValue: '25000', additionalInfo: 'Minimum income $25,000 p.a.' },
        { eligibilityType: 'MIN_AGE', additionalValue: '18' },
        { eligibilityType: 'RESIDENCY', additionalInfo: 'Australian residents only' },
      ],
      fees: [
        { name: 'Application Fee', feeType: 'UPFRONT', amount: '250.00', additionalInfo: 'One-off application fee' },
        { name: 'Monthly Fee', feeType: 'PERIODIC', amount: '8.00', additionalInfo: 'Monthly loan fee' },
      ],
      depositRates: [],
      lendingRates: [
        { lendingRateType: 'FIXED', rate: '0.0999', comparisonRate: '0.1145', calculationFrequency: 'P1D', applicationFrequency: 'P1M', additionalInfo: 'Fixed rate 9.99% p.a. for 1-7 year terms. Comparison rate 11.45% p.a.' },
      ],
    },
  ],
};
